/**
 * next8 Phase 1 — BUSINESS HANDOFF (plan1_final_v2 §6 + §16).
 *
 * A sentence that IS a business transaction but was not fully specified does not
 * produce a card. It produces a HANDOFF: a server-generated ticket that opens a
 * dedicated form (Phase 2+), pre-filled with what the sentence already carried
 * and carrying the SLOT STATES the form still needs to fill. plan §16 fixes the
 * order — route → screen → entity resolution — so the handoff exists BEFORE the
 * entity is known, and an AMBIGUOUS/MISSING party is a state the screen renders,
 * not a dead end in chat.
 *
 * Why this is its own module and not `session-context.mjs`:
 *  - Session context answers "what was the user just talking about", and every
 *    entry carries PROVENANCE (user_selected vs derived) so only a user-chosen
 *    entity may seed a WRITE. A handoff is the opposite kind of thing: it is
 *    generated BY THE SERVER, has no provenance, and is only ever read back by
 *    the principal + conversation it was issued to.
 *  - Reusing the context store would have meant teaching `set()` about a kind
 *    with no provenance, i.e. weakening the one invariant that keeps a fuzzy
 *    READ match from driving a money document. Two different questions, two
 *    stores; the context store keeps its meaning.
 *
 * Safety properties (all tested in test/next8-collect-handoff.test.mjs):
 *  - SERVER-GENERATED id. A client may never mint a handoff_id — nothing here
 *    accepts one from outside.
 *  - PRINCIPAL + CONVERSATION BOUND. `readHandoff` refuses another principal's
 *    (or another conversation's) ticket, and the refusal does not leak whether
 *    the id exists at all.
 *  - NO AUTHORITATIVE NUMBER EVER TRAVELS. The prefill carries ids, labels and
 *    STATES — never an amount, never an outstanding. Amounts come from ERPNext
 *    at propose time (Phase 3), which is also why "prefill is not authority".
 *  - STALE IS NOT AN EXPIRY. The TTL here only bounds memory of a conversation
 *    that was abandoned; whether the DOCUMENT data is still valid is decided by
 *    re-reading ERPNext at propose/execute time (plan §5.3), never by this TTL.
 */

import { randomUUID } from "node:crypto";

/**
 * Slot states, deliberately the SAME vocabulary the entity-resolution policy
 * speaks (plan §4.3): a screen and the chat pipeline must not describe the same
 * situation with two different words.
 */
export const SLOT_STATES = Object.freeze({
  RESOLVED: "RESOLVED",
  AMBIGUOUS: "AMBIGUOUS",
  MISSING: "MISSING",
  NO_MATCH: "NO_MATCH",
});

/** The payload's `type` field — exactly the string plan §6 names (`business_handoff`). */
export const HANDOFF_TYPE = "business_handoff";

/** Machine code for the stale-refusal (upper snake, like every other code here). */
export const HANDOFF_STALE_CODE = "STALE_HANDOFF";

/** Only the screens the contract actually knows how to open. */
export const HANDOFF_SCREENS = Object.freeze({
  "payment.collect": "collect",
  "payment.create": "collect",
  // Phase 6 — the sales screen: a sale is its own vertical (lines + discounts
  // + optional same-command collection), not a collect with extra fields.
  "sales.create": "sales",
  // Phase 7 — the purchase screen: buying from a supplier is its own vertical
  // (supplier + lines at the BUYING price + an optional advance payment), and
  // its money direction is the MIRROR of a sale (Pay, not Receive).
  "purchase_invoice.create": "purchase",
});

/** How long an unfinished handoff stays readable. NOT a freshness guarantee. */
export const HANDOFF_TTL_MS = 30 * 60 * 1000; // 30m — one conversation's length

function assertSlotState(state, where) {
  if (!Object.values(SLOT_STATES).includes(state)) {
    throw Object.assign(
      new Error(`trạng thái slot "${state}" không hợp lệ ở ${where} (chỉ nhận ${Object.values(SLOT_STATES).join("|")})`),
      { code: "HANDOFF_SLOT_STATE_INVALID" },
    );
  }
  return state;
}

/**
 * Canonical id for the ONE executable collect flow. The alias question (§6.5) is
 * settled in the contract (`resolveCapabilityId`); this module only needs to know
 * which screen a capability opens, so an alias and its canonical id land on the
 * same screen instead of two.
 *
 * @param {string} capabilityId
 * @returns {string|null} screen id, or null when this capability has no screen
 */
export function screenForCapability(capabilityId) {
  return HANDOFF_SCREENS[capabilityId] ?? null;
}

/**
 * Build the payload the client opens a screen with.
 *
 * `prefill` values are {state, id?, label?, candidates?} — id/label only ever
 * come from a resolution the caller already made (or from the user's own words
 * for a label), and candidates are the picker rows. No amount, ever.
 *
 * @param {object} args
 * @param {string} args.capability canonical capability id (e.g. payment.create)
 * @param {string} args.principalId server-resolved principal (NEVER a body field)
 * @param {string|null} [args.conversationId]
 * @param {string} [args.question] the utterance, echoed for the screen's header
 * @param {object} [args.prefill] slot name → {state, id?, label?, candidates?}
 * @param {number} [args.issuedAt] test seam (defaults to now)
 * @returns {{type:string, handoff_id:string, capability:string, screen:string,
 *            question:string, prefill:object, issued_at:string}}
 */
export function buildHandoff({
  capability,
  principalId,
  conversationId = null,
  question = "",
  prefill = {},
  issuedAt = Date.now(),
} = {}) {
  const screen = screenForCapability(capability);
  if (!screen) {
    throw Object.assign(new Error(`capability "${capability}" không có màn hình để mở`), {
      code: "HANDOFF_NO_SCREEN",
    });
  }
  if (typeof principalId !== "string" || principalId.trim() === "") {
    // A handoff with no owner could be claimed by anyone — fail closed instead
    // of issuing an unowned ticket.
    throw Object.assign(new Error("thiếu principal cho handoff"), { code: "HANDOFF_NO_PRINCIPAL" });
  }
  const slots = {};
  for (const [slot, value] of Object.entries(prefill)) {
    if (!value || typeof value !== "object") {
      throw Object.assign(new Error(`prefill.${slot} phải là object`), { code: "HANDOFF_PREFILL_INVALID" });
    }
    assertSlotState(value.state, `prefill.${slot}`);
    if (value.amount_vnd !== undefined || value.outstanding_vnd !== undefined || value.amount !== undefined) {
      // The one rule that keeps "prefill is not authority" true by construction:
      // no number can even enter the ticket, so no client can later claim the
      // server told it a total.
      throw Object.assign(
        new Error(`prefill.${slot} không được mang số tiền — số tiền chỉ đến từ ERPNext ở bước propose`),
        { code: "HANDOFF_AMOUNT_FORBIDDEN" },
      );
    }
    slots[slot] = { ...value };
  }
  return {
    type: HANDOFF_TYPE,
    handoff_id: randomUUID(),
    capability,
    screen,
    question: String(question ?? ""),
    prefill: slots,
    issued_at: new Date(issuedAt).toISOString(),
  };
}

/**
 * The store is deliberately tiny and in-process: a handoff only has to survive
 * the gap between a chat turn and the screen the user taps. The durable state in
 * this system is the idempotency ledger, and the authoritative state is ERPNext.
 */
export class HandoffStore {
  constructor({ now = Date.now } = {}) {
    /** @type {Map<string, {handoff:object, principalId:string, conversationId:string|null, ts:number}>} */
    this.entries = new Map();
    this.now = now;
  }

  /**
   * @param {object} handoff as returned by buildHandoff()
   * @param {{principalId:string, conversationId?:string|null, ts?:number}} owner
   */
  put(handoff, { principalId, conversationId = null, ts } = {}) {
    if (!handoff?.handoff_id) {
      return { ok: false, code: "HANDOFF_ID_MISSING" };
    }
    if (typeof principalId !== "string" || principalId.trim() === "") {
      // Mirrors session-context's `.ok` contract: a refusal is RETURNED, never
      // thrown, and every call site is expected to check `.ok` — the next8/D1
      // lesson (a silent `ok:false` made a whole feature unreachable).
      return { ok: false, code: "HANDOFF_NO_PRINCIPAL" };
    }
    this.entries.set(handoff.handoff_id, {
      handoff,
      principalId,
      conversationId: conversationId ?? null,
      ts: ts ?? this.now(),
    });
    return { ok: true };
  }

  /**
   * Read a handoff back, enforcing ownership.
   *
   * A ticket belonging to another principal/conversation is reported exactly like
   * an id that never existed (`HANDOFF_STALE`): the caller must not be able to
   * probe which handoff ids are alive.
   *
   * @returns {{ok:true, handoff:object}|{ok:false, code:string}}
   */
  read(handoffId, { principalId, conversationId = null, now } = {}) {
    if (typeof handoffId !== "string" || handoffId.trim() === "") {
      return { ok: false, code: HANDOFF_STALE_CODE };
    }
    const entry = this.entries.get(handoffId);
    if (!entry) return { ok: false, code: HANDOFF_STALE_CODE };
    const at = now ?? this.now();
    if (at - entry.ts > HANDOFF_TTL_MS) {
      this.entries.delete(handoffId);
      return { ok: false, code: HANDOFF_STALE_CODE };
    }
    if (entry.principalId !== (principalId ?? null)) {
      return { ok: false, code: HANDOFF_STALE_CODE };
    }
    // A conversation ids present on both sides must match; a missing one on
    // either side keeps the pre-NEXT6 behaviour (no conversation = one thread).
    if (entry.conversationId && conversationId && entry.conversationId !== conversationId) {
      return { ok: false, code: HANDOFF_STALE_CODE };
    }
    return { ok: true, handoff: entry.handoff };
  }

  /** Test seam: forget everything (a fresh process has the same state). */
  clear() {
    this.entries.clear();
  }
}

/**
 * Module-level store used by the pipeline. Exported so a test can reset it —
 * the same seam session-context offers.
 */
export const handoffStore = new HandoffStore();

/**
 * The slot states a collect sentence produced, in the vocabulary the screen and
 * the pipeline share. Kept here (not in the pipeline) so both the chat wiring and
 * the /collect/propose route describe the SAME state machine.
 *
 * @param {object} args
 * @param {object|null} args.customer resolved customer row (or null)
 * @param {boolean} [args.ambiguousCustomer]
 * @param {boolean} [args.amountGiven] whether the sentence carried a number
 * @param {boolean} [args.hasOpenInvoices] whether the customer has open invoices
 */
export function collectSlotStates({
  customer = null,
  ambiguousCustomer = false,
  amountGiven = false,
  hasOpenInvoices = null,
} = {}) {
  const customerState = ambiguousCustomer
    ? SLOT_STATES.AMBIGUOUS
    : customer
      ? SLOT_STATES.RESOLVED
      // "no row at all" and "a row that is not this name" are the same situation
      // for the screen: it must ask. NONE vs NO_MATCH is a router-level nuance a
      // form cannot act differently on.
      : SLOT_STATES.MISSING;
  return {
    customer: customerState,
    // Owner lock §6.3 lives here: open invoices ⇒ the user MUST allocate. Zero
    // open invoices is the ONE case where "no allocation" is a legitimate answer
    // (on-account), so the slot reads NO_MATCH instead of MISSING — the screen
    // then offers the advance path with its own copy instead of blocking.
    allocations: hasOpenInvoices === false ? SLOT_STATES.NO_MATCH : SLOT_STATES.MISSING,
    payment_methods: SLOT_STATES.MISSING,
    amount: amountGiven ? SLOT_STATES.RESOLVED : SLOT_STATES.MISSING,
  };
}
